language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
- platformio lib install 75
- platformio lib install 19
script:
- platformio run
after_success: ./scripts/upload-binary.sh
env:
  global:
    secure: gdXi/pjHz26ezZqFRmCxlOjjJSZTxhwCnqqbzn3QK1CYNEwKEp87niIz0O/GhfCnGCwTVirDv/eeYn+kje9kLvLXy+wAhTOwLf137p3lLtPuNe12tB4x1KN/WfHMDYsT4JRcLKupthvZT7yMPLLIDPSymgU8s40Bn2XmGFKWY7ubPhgyhUK6luNShK11D+aZVlOKXahdAh2Idr7O9XxoW0g9KcZYLhfccQaDGg5Gt8o+0NIyIBMCEVsR6dLV3v767F9seMdVVDdMDOhRaaKW+VTSbbP/5zQ89bQ97vf5mOm6stpeweJZN7oGcbhMSDTM90CPXd5l8XOmtG85qtOUEDt90vlRSPCrD9XYjvtNpt0xnKLVJyrmUW8PdIigNvg5L6McSkrVQJeLW8Pki9e8+tTQzl39Icx4LdYH5rtZiFM8Micl1cOXQl7L/FCZGFOTACCxD5XzIInlVLjdWts5k/tPO9AkR9IibRyzI09kWvXEXd48a85g0ZKlyvooIfaREGIXcGLDkK6QW1Wwbo4V22HhQhsXyAU2SVxDyUrVuN/PrMRTHHxWCsiNLmQY3XgsqLm9SAQ83AlkzNCgrrpcaQc1iLamScvrJq5mfbdqdHhl/wQiHRcFpFs2YZHT6I3Ean/dmdhVWo3/bN/rdbpSLBBKAr4EaX+ZcHIfaX4nVWk=
